#!/usr/bin/env julia

const tag = "juliagpu/julia"

# list available images
const bases = readdir(joinpath(@__DIR__, "base"))
const derivatives = readdir(joinpath(@__DIR__, "derived"))

# process arguments
const builds = if length(ARGS) == 0
    # rebuild everything
    bases ∪ derivatives
else
    ARGS
end

for base in bases
    base_path = joinpath(@__DIR__, "base", base)
    base_tag = "$tag:$base"

    if base in builds
        run(`docker build --pull --no-cache $base_path --tag $base_tag`)
        run(`docker push $base_tag`)
    end

    for derived in derivatives
        derived_path = joinpath(@__DIR__, "derived", derived)
        derived_tag = "$tag:$base-$derived"

        if base in builds || derived in builds
            run(`docker build --pull --build-arg base=$base $derived_path --tag $derived_tag`)
            run(`docker push $derived_tag`)
        end
    end
end
