#!/usr/bin/env julia

const tag = "juliagpu/julia"

const verbose = haskey(ENV, "VERBOSE")
docker_build = if verbose
    `docker build`
else
    `docker build --quiet`
end

# list available images
const bases = readdir(joinpath(@__DIR__, "base"))
const derivatives = readdir(joinpath(@__DIR__, "derived"))

# process arguments
const builds = if length(ARGS) == 0
    # rebuild everything
    bases ∪ derivatives
else
    ARGS
end

for base in bases
    base_path = joinpath(@__DIR__, "base", base)
    base_tag = "$tag:$base"

    if base in builds
        verbose && @info("Rebuilding base image $base")
        run(`$docker_build --no-cache $base_path --tag $base_tag`)
    end

    for derived in derivatives
        derived_path = joinpath(@__DIR__, "derived", derived)
        derived_tag = "$tag:$base-$derived"

        if base in builds || derived in builds
            verbose && @info("Rebuilding derived image $base-$derived")
            run(`$docker_build --build-arg base=$base $derived_path --tag $derived_tag`)
        end
    end
end
